In [3]:
import pandas as pd
import subprocess
import sys
import numpy as np
import os
import shutil

In [4]:
def shell_do(command, log=False, return_log=False):
    print(f'Executing: {(" ").join(command.split())}', file=sys.stderr)

    res=subprocess.run(command.split(), stdout=subprocess.PIPE)

    if log:
        print(res.stdout.decode('utf-8'))
    if return_log:
        return(res.stdout.decode('utf-8'), res.stderr.decode('utf-8'))

# Interacting with Swiss Army Knife through Jupyter Notebooks
## What is Swiss Army Knife?
### Swiss Army Knife is a generic app which can be used to perform common file operations for the genotype data housed on DNANexus.
### Contains software such as plink, plink2, bcftools, etc.
#### Below we'll see an example of looping through each chromosome and extracting a set of variants.
##### -iin: input (need to specify each file).
##### -icmd: command to run
##### --instance-type: VM type to run the command on
##### --destination: output folder
#### Note: this will start 23 separate Swiss Army Knife jobs so make sure you are using a reasonable instance type.

In [5]:
import pandas as pd

In [6]:
!dx download ADRD_noFTD_noPARKINSONISM_noALS_noVD_noHT_noCJD_noPDD.CTRL_inclProxy_60older.plink_pheno.txt

Error: path "/opt/notebooks/ADRD_noFTD_noPARKINSONISM_noALS_noVD_noHT_noCJD_no
PDD.CTRL_inclProxy_60older.plink_pheno.txt" already exists but -f/--overwrite
was not set

In [7]:
df = pd.read_csv("ADRD_noFTD_noPARKINSONISM_noALS_noVD_noHT_noCJD_noPDD.CTRL_inclProxy_60older.plink_pheno.txt", sep = '\t')

In [8]:
df.head()

       FID      IID  ADRD
0  1010117  1010117     2
1  1012224  1012224     2
2  1013262  1013262     2
3  1015072  1015072     2
4  1016036  1016036     2

In [9]:
count_1 = df['ADRD'].value_counts().get(1, 0)
count_2 = df['ADRD'].value_counts().get(2, 0)

print(f"Count of 1 in 'Pheno': {count_1}")
print(f"Count of 2 in 'Pheno': {count_2}")

Count of 1 in 'Pheno': 87524
Count of 2 in 'Pheno': 3290

In [20]:
!dx download UKB_EUR_UMAP_COVARIATES.txt

The given path "UKB_EUR_UMAP_COVARIATES.txt" resolves to the following data objects:
0) closed  2025-05-12 20:26:23 75.05 MB  UKB_EUR_UMAP_COVARIATES.txt (file-J0V5XpjJbP2Qj45j9Q76VyPq)
1) closed  2024-08-29 18:37:14 75.05 MB  UKB_EUR_UMAP_COVARIATES.txt (file-Gp7Vq5QJ2ZfYkFbvQ29433p9)

Pick a numbered choice:

^C

In [19]:
df1 = pd.read_csv("UKB_EUR_UMAP_COVARIATES.txt", sep = '\t')

FileNotFoundError: [Errno 2] No such file or directory: 'UKB_EUR_UMAP_COVARIATES.txt'

In [ ]:
# Extract only 'FID' and 'IID' column values
final2 = df[['FID', 'IID']]

In [43]:
final2.head()

       FID      IID
0  1000068  1000068
1  1000910  1000910
2  1001643  1001643
3  1002105  1002105
4  1002209  1002209

In [44]:
final2.to_csv("FID_IID_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt", sep='\t', index=False)

In [46]:
df.head()

       FID      IID  ADRD
0  1010117  1010117     2
1  1012224  1012224     2
2  1013262  1013262     2
3  1015072  1015072     2
4  1016036  1016036     2

In [ ]:
df.to_csv("Pheno_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt", sep='\t', index=False)

In [47]:
# Merging the DataFrames on the 'ID' column
final4 = pd.merge(final2, df, on=['FID','IID'], how='inner')

print("Merged DataFrame:")
final4.head()

Merged DataFrame:

       FID      IID  ADRD
0  1000068  1000068     1
1  1000910  1000910     1
2  1001643  1001643     1
3  1002105  1002105     1
4  1002209  1002209     1

In [48]:
count_1 = final4['ADRD'].value_counts().get(1, 0)
count_2 = final4['ADRD'].value_counts().get(2, 0)

print(f"Count of 1 in 'Pheno': {count_1}")
print(f"Count of 2 in 'Pheno': {count_2}")

Count of 1 in 'Pheno': 83205
Count of 2 in 'Pheno': 3105

In [49]:
final4.to_csv("Covar_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt", sep='\t', index=False)

In [50]:
!dx upload Pheno_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt

[===========================================================>] Uploaded 1,553,593 of 1,553,593 bytes (100%) Phano_Pheno_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New_sbp.txt
ID                                file-GxfvjZ0JbP2zPqg4Z4q1BJkg
Class                             file
Project                           project-GkYf2zQJbP2Q3vFgf14863Gf
Folder                            /
Name                              Phano_Pheno_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New_sbp.txt
State                             closing
Visibility                        visible
Types                             -
Properties                        -
Tags                              -
Outgoing links                    -
Created                           Thu Dec 26 21:36:16 2024
Created by                        vidhu
 via the job                      job-Gxfjkb0JbP2YPFbjv45zgb9Q
Last modified                     Thu Dec 26 21:36:17 2024
Media type
archivalState                     "live"
cloudAccount                      "cloudaccount-dnanexus"

In [45]:
!dx upload FID_IID_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt

[===========================================================>] Uploaded 1,380,968 of 1,380,968 bytes (100%) FID_IID_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New_sbp.txt
ID                                file-Gxfvg08JbP2jKYyy6VV02v4Z
Class                             file
Project                           project-GkYf2zQJbP2Q3vFgf14863Gf
Folder                            /
Name                              FID_IID_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New_sbp.txt
State                             closing
Visibility                        visible
Types                             -
Properties                        -
Tags                              -
Outgoing links                    -
Created                           Thu Dec 26 21:32:49 2024
Created by                        vidhu
 via the job                      job-Gxfjkb0JbP2YPFbjv45zgb9Q
Last modified                     Thu Dec 26 21:32:50 2024
Media type
archivalState                     "live"
cloudAccount                      "cloudaccount-dnanexus"

In [39]:
!dx upload Covar_New_final_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt

[===========================================================>] Uploaded 15,224,174 of 15,224,174 bytes (100%) Pheno_New_final_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New_sbp.txt
ID                                file-GxfvGzjJbP2bJyzkjg7V47gZ
Class                             file
Project                           project-GkYf2zQJbP2Q3vFgf14863Gf
Folder                            /
Name                              Pheno_New_final_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New_sbp.txt
State                             closing
Visibility                        visible
Types                             -
Properties                        -
Tags                              -
Outgoing links                    -
Created                           Thu Dec 26 21:11:27 2024
Created by                        vidhu
 via the job                      job-Gxfjkb0JbP2YPFbjv45zgb9Q
Last modified                     Thu Dec 26 21:11:28 2024
Media type
archivalState                     "live"
cloudAccount                      "cloudaccount-dnanexus"

In [53]:
%%bash

seq 1 1 23 > chr_list.txt

FILE_DIR_A="/Imputed_Genotypes_2023/TOPMed_Plink2"
FILE_DIR_B="/ref_panel/chip_overlaps/"
# FILE_DIR_C="/Imputed_Genotypes_2023/TOPMed_Plink2/extract"

CHR_IDS=$(cat chr_list.txt)


for CHR in $CHR_IDS; do
    dx run swiss-army-knife -iin="chr${CHR}_pgen.pgen" \
    -iin="chr${CHR}_pgen.psam" \
    -iin="chr${CHR}_pgen.pvar" \
    -iin="Pheno_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt" \
    -iin="Covar_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt" \
    -iin="FID_IID_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt" \
    -icmd='plink2 --pfile "$in_prefix" \
    --glm hide-covar firth-fallback cols=+a1freq,+a1freqcc,+a1countcc,+totallelecc,+err,+beta,-test,-nobs,-tz,-orbeta \
    --pheno Pheno_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt --maf 0.01 \
    --pheno-name ADRD --covar-variance-standardize \
    --geno 0.05 --mac 20  --memory 12000 \
    --covar Covar_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt \
    --covar-name PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,GENETIC_SEX,AGE_2024_COV,sbp \
    --keep FID_IID_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt \
    --out "$in_prefix".HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt' -y  --brief --priority normal \
    --instance-type mem3_ssd3_x12 --destination "${projectid}:${FILE_DIR}/" 
done

job-Gxfvk90JbP2qkqKPv2qkKyyV
job-Gxfvk98JbP2Z91v1b7zfvzKb
job-Gxfvk9QJbP2fG2QQQgfV8kpG
job-Gxfvk9jJbP2Qb2ypGxgj98QG
job-GxfvkB0JbP2fG2QQQgfV8kpQ
job-GxfvkB8JbP2qkqKPv2qkKyyb
job-GxfvkBQJbP2Z91v1b7zfvzKj
job-GxfvkBjJbP2Z91v1b7zfvzKp
job-GxfvkF0JbP2pG9qPGBgPxb44
job-GxfvkF8JbP2fG2QQQgfV8kqQ
job-GxfvkFQJbP2Qb2ypGxgj98QQ
job-GxfvkFjJbP2pG9qPGBgPxb48
job-GxfvkG0JbP2fG2QQQgfV8kqX
job-GxfvkG8JbP2ZZ9jJv5VV29JX
job-GxfvkGjJbP2ZZ9jJv5VV29JZ
job-GxfvkJ0JbP2qzPkKPJ6p9GXy
job-GxfvkJ8JbP2k8Jf4QkVvK3qQ
job-GxfvkJQJbP2qzPkKPJ6p9GY6
job-GxfvkJjJbP2ZZ9jJv5VV29KB
job-GxfvkK0JbP2fG2QQQgfV8kv7
job-GxfvkK8JbP2qzPkKPJ6p9GYB
job-GxfvkKQJbP2k8Jf4QkVvK3qv
job-GxfvkKjJbP2Qb2ypGxgj98V5

In [9]:
!dx download chr9_pgen.HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt.ADRD.glm.logistic.hybrid

[===========================================================>] Completed 45,228,068 of 45,228,068 bytes (100%) /opt/notebooks/chr9_pgen.Pheno_New_final_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New_sbp.txt.ADRD.glm.logistic.hybridd

In [23]:
import pandas as pd
for CHR in range(1,23):
    print(CHR)
    AGE_SEX_MATCH_TEMP = pd.read_csv(f'chr{CHR}_pgen.Pheno_New_final_HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New_sbp.txt.ADRD.glm.logistic.hybrid',
        delim_whitespace=True
    )
    if CHR==1:
        AGE_SEX_MATCH = AGE_SEX_MATCH_TEMP
    else:
        AGE_SEX_MATCH = pd.concat([AGE_SEX_MATCH,AGE_SEX_MATCH_TEMP])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22

In [142]:
%%bash
head chr19_pgen.HT+DEM_VS_HT_TOWNSEND.Pheno.glm.logistic.hybrid

#CHROM	POS	ID	REF	ALT	A1	A1_CASE_CT	A1_CTRL_CT	CASE_ALLELE_CT	CTRL_ALLELE_CT	A1_FREQ	A1_CASE_FREQ	A1_CTRL_FREQ	FIRTH?	BETA	SE	P	ERRCODE
19	119135	19:119135:C:G	C	G	G	138.75	2153.68	11944	188162	0.0114561	0.0116167	0.0114459	N	0.0294587	0.135091	0.827378	.
19	125962	19:125962:T:A	T	A	A	141.168	2218.75	11944	188162	0.0117933	0.0118192	0.0117917	N	0.00873895	0.134434	0.94817	.
19	133816	19:133816:GTTCTC:G	GTTCTC	G	G	181.187	2684.76	11944	188162	0.0143222	0.0151697	0.0142684	N	0.137173	0.112182	0.221416	.
19	140292	19:140292:C:T	C	T	T	126.385	2043.92	11944	188162	0.0108458	0.0105815	0.0108626	N	-0.0638601	0.145922	0.661653	.
19	225487	19:225487:C:T	C	T	T	129.598	2225.85	11944	188162	0.011771	0.0108504	0.0118295	N	-0.102351	0.0961457	0.287085	.
19	230429	19:230429:C:T	C	T	T	176.327	2733.76	11944	188162	0.0145427	0.0147628	0.0145288	N	0.0256584	0.0935784	0.783938	.
19	231076	19:231076:TAAAAAG:T	TAAAAAG	T	T	494.923	7670.91	11944	188162	0.0408075	0.0414369	0.0407676	N	0.0188984	0.0504384	0.707897	.
19	236454	19:236454:G:A	G	A	A	119.826	1893.72	11944	188162	0.0100624	0.0100323	0.0100643	N	-0.00630741	0.146846	0.965739	.
19	240554	19:240554:C:T	C	T	T	314.895	5113.3	11944	188162	0.0271266	0.0263643	0.027175	N	-0.0365032	0.0616956	0.554075	.

In [24]:
AGE_SEX_MATCH.to_csv("HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt", sep='\t', index=False)

In [25]:
!dx upload HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New.txt

[===========================================================>] Uploaded 1,057,769,536 of 1,057,769,536 bytes (100%) HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New_sbp.txt
ID                                file-GxgGvk0JbP2VG03037f9Q24Q
Class                             file
Project                           project-GkYf2zQJbP2Q3vFgf14863Gf
Folder                            /
Name                              HT_Dem_remove_PD_VD_FTD_Hu_CJD_Vs_HT_New_sbp.txt
State                             closing
Visibility                        visible
Types                             -
Properties                        -
Tags                              -
Outgoing links                    -
Created                           Fri Dec 27 15:57:24 2024
Created by                        vidhu
 via the job                      job-GxgF3f0JbP2pzzZF6vYjjb0v
Last modified                     Fri Dec 27 15:57:26 2024
Media type
archivalState                     "live"
cloudAccount                      "cloudaccount-dnanexus"